<?php

namespace app\modules\admin\controllers;


use app\models\PremiumRates;
use app\models\PremiumRatesSearch;
use Yii;
use yii\filters\VerbFilter;
use yii\web\Controller;

class PremiumController extends Controller
{
    public $layout = 'ml_admin.php';


    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    public function beforeAction($action)
    {
        if (Yii::$app->user->isGuest) {
            Yii::$app->response->redirect(['account#login']);
        }

        Yii::$app->view->params['menu'] = Yii::$app->getModule('admin')->params['menu'];

        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }

    public function actionIndex() : string
    {
        $searchModel = new PremiumRatesSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }
    
    public function actionCreate() : string 
    {
        $model = Yii::createObject(PremiumRates::className());

        if($model->load(Yii::$app->request->post()) && $model->create() ) {
            $this->redirect('index');
        }
        
        return $this->render('create', [
            'model' => $model
        ]);
    }
    
    public function actionUpdate($id) : string
    {
        $model = (new PremiumRates())
            ->findOne(['id' => $id]);

        $model->duration = (int) $model->duration/24;
        if($model->load(Yii::$app->request->post()) && $model->create() ) {
            $this->redirect('index');
        }

        return $this->render('edit', [
            'model' => $model
        ]);
    }
    
    public function actionDelete(int $id) : PremiumController
    {
        $model = (new PremiumRates())
        ->findOne(['id' => $id]);

        return $this->redirect(['index']);
    }
}