<?php
/**
 * Created by PhpStorm.
 * User: Tony
 * Date: 08.02.2019
 * Time: 18:36
 */

namespace app\modules\admin\controllers;

use app\models\UserSearch;
use mdm\admin\controllers\UserController as RBACUser;
use Yii;

class UserController extends RBACUser
{
    public $layout = 'ml_admin.php';

    public function beforeAction($action)
    {
        if (Yii::$app->user->isGuest) {
            Yii::$app->response->redirect(['account#login']);
        }

        \Yii::$app->view->params['menu'] = \Yii::$app->getModule('admin')->params['menu'];

        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }

    public function actionIndex()
    {
        $searchModel = new UserSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }
}