<?php
/**
 * Created by PhpStorm.
 * User: Tony
 * Date: 11.02.2019
 * Time: 7:33
 */

namespace app\modules\admin\models;


use app\models\Settings as Settings;
use yii\base\Model;

/**
 * This is the model class for main settings page ActiveForm.
 *
 * @property int $id
 * @property array $name
 * @property array $option_value
 * @property array $site_name
 * @property array $site_email
 * @property array $site_facebook
 * @property array $site_telegram
 * @property array $site_instagram
 * @property array $site_viber
 */
class SettingsFormModel extends Model
{
    public $site_name;
    public $site_email;
    public $site_facebook;
    public $site_telegram;
    public $site_instagram;
    public $site_viber;
    public $site_maintenance = 'Off';

    public function rules()
    {
        return [
            [['site_name', 'site_email', 'site_facebook', 'site_instagram', 'site_viber', 'site_telegram'], 'safe'],
            [['site_name', 'site_facebook', 'site_instagram', 'site_viber', 'site_telegram'], 'string'],
            [['site_email'], 'email'],
        ];
    }

    public function beforeSave($insert)
    {
        echo "<pre>";
        print_r($insert);
        echo "</pre>";
//        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }

    public function validate($attributeNames = null, $clearErrors = true)
    {
        return parent::validate($attributeNames, $clearErrors); // TODO: Change the autogenerated stub
    }

    public function save($runValidation = true, $attributeNames = null)
    {
        if (! $this->validate()) {
            return false;
        }

        $attributes = get_object_vars($this);
        $settings  = \Yii::createObject(Settings::className());

        foreach ($attributes as $attribute => $val) {
            $model = $settings->find()->where(['name' => $attribute])->one();

            if(! empty($val)) {
                $model->option_value = $val;
                $model->save();
            }
        }
        return true;
    }

//    public function load($data, $formName = null)
//    {
//        echo "<pre>";
//        print_r($data);
//        echo "</pre>";
//    }

}