<?php
/**
 * Created by PhpStorm.
 * User: Tony
 * Date: 19.02.2019
 * Time: 14:16
 */

namespace app\modules\myaccount\models;


use app\models\AdvertiseCitiesRegions;
use app\models\AdvertisementPost;
use app\models\Cities;
use yii\base\Model;

class CreateAdvertisementPost extends Model
{
    public $title;
    public $category_id;
    public $subCat_id;
    public $description;
    public $pricePerMonth;
    public $distancePerMonth;
    public $authorId;
    public $advertise_type;
    public $sticking_area;
    public $contract_term;
    public $city;
    public $city_district;
    public $coverage;
    public $show_email;
    public $published_at;

    public function rules()
    {
        return [
            [['title', 'authorId', 'category_id', 'subCat_id', 'pricePerMonth', 'published_at'], 'required'],
            [['title', 'description'], 'string'],
            [['distancePerMonth', 'pricePerMonth'], 'number'],
            [['show_email'], 'boolean'],
            [['show_email'], 'default', 0],
        ];
    }

    public function validate($attributeNames = null, $clearErrors = true)
    {
        return parent::validate($attributeNames, $clearErrors); // TODO: Change the autogenerated stub
    }

    public function createAdvertisement()
    {
        if(! $this->validate()) {
            return false;
        } else {
            $advertisement = new AdvertisementPost();
            $cities = new Cities();
            $advCityRegions = new AdvertiseCitiesRegions();

            $advertisement->title = $this->title;
            $advertisement->category_id = $this->category_id;
            $advertisement->subCat_id = $this->subCat_id;
            $advertisement->description = $this->description;
        }

    }

}