<?php

namespace app\modules\myaccount\models;


use app\models\Profile;
use app\models\User;
use Yii;
use yii\base\Model;

class EditProfileForm extends Model
{
    public $username;
    public $email;
    public $address;
    public $phone;
    public $viber;
    public $telegram;
    public $whatsapp;
    public $site;
    public $profile_image;
    public static $usernameRegExp = '/^[a-zA-Zа-яёА-ЯЁ(\ a-zA-Zа-яёА-ЯЁ)?]+$/';
    private $_user = false;

    public function rules()
    {
        return [
            'usernameTrim'     => ['username', 'trim'],
            'usernameRequired' => ['username', 'required', 'on' => ['register', 'create', 'connect', 'update']],
            'usernameMatch'    => ['username', 'match', 'pattern' => self::$usernameRegExp],
            'usernameLength'   => ['username', 'string', 'min' => 3, 'max' => 255],
            ['email','email'],
            'addressTrim'     => ['address', 'trim'],
            'phoneTrim'    => ['phone', 'trim'],
            'viberTrim'    => ['viber', 'trim'],
            'whatsappTrim' => ['whatsapp', 'trim'],
            'siteTrim'     => ['site', 'trim'],
            'telegramTrim' => ['telegram', 'trim']
        ]; // TODO: Change the autogenerated stub
    }

    public function validate($attributeNames = null, $clearErrors = true)
    {
        if (!$this->hasErrors()) {
            return true;
        }
    }
    
    public function editProfile()
    {
        $userData = \Yii::$app->user;
        $profile = Profile::findOne(['user_id'=>$userData->getId()]);
        $user = User::findOne(['id'=>$userData->getId()]);
        $user->username = (!empty($this->username))? $this->username: $user->username;
        $profile->public_email = (!empty($this->email)) ?$this->email: $profile->public_email;
        $profile->phone = (!empty($this->phone))? $this->phone : $profile->phone;
        $profile->viber = (!empty($this->viber)) ? $this->viber: $profile->viber;
        $profile->telegram = (!empty($this->telegram)) ? $this->telegram : $profile->telegram;
        $profile->website = (!empty($this->site)) ? $this->site : $profile->website;
        $profile->whatsapp = (!empty($this->whatsapp)) ? $this->whatsapp : $profile->whatsapp;
        if( $profile->save() && $user->save()){
            return true;
        }
        else{
            $errors = $profile->errors;
        }
        return false;
    }

    public function getUser()
    {
        if ($this->_user === false) {
            $this->_user = User::findByEmail($this->email);
        }

        return $this->_user;
    }

    public function saveImage($filename)
    {
        $profile = Profile::findOne(['user_id'=>Yii::$app->user->getId()]);
        $profile->profile_image = $filename;
        $profile->save();
    }

    public function attributeLabels()
    {
        return [
            'username' => Yii::t('app','Имя'),
            'address' => Yii::t('app','Адрес'),
            'phone' => Yii::t('app','Телефон'),
        ];
    }
}