<?php
/**
 * Created by PhpStorm.
 * User: Tony
 * Date: 16.02.2019
 * Time: 15:13
 */

namespace app\widgets;


use Yii;
use yii\base\Widget;
use yii\widgets\ActiveForm;
use app\models\SiteSearch;
use \app\modules\admin\models\Categories;
use app\models\Cities;

class SearchAdverts extends Widget
{
    public function run()
    {
        $model = \Yii::createObject(SiteSearch::className());
        $categories = Yii::createObject(Categories::className());
        $subList = array_merge([0 => Yii::t('app', 'Категория')], $categories->subAdvertisement);
        $cities = Yii::createObject(Cities::className())->cities;
        ?>
        <div class="form-search">
            <div class="container">
                <a class="search-query" href="#">Поисковый запрос</a>
                <div class="holder-form-search">
                    <span class="bg-search"></span>
                    <?php $form = ActiveForm::begin(); ?>
                        <fieldset>
                            <a class="closed-search-form" href="#"></a>
                            <?= $form->field($model,'textRequest', ['options' => ['class' => 'search-input', 'tag' => 'div']])
                                ->label(false)
                                ->textInput(['placeholder' => \Yii::t('app', 'Поисковый запрос')])?>
                            <?= $form->field($model, 'categoryId', ['options' => ['class' => 'category-input', 'tag' => 'div']])
                                ->label(false)
                                ->dropDownList($subList, ['class' => 'dropdown']) ?>
                            <div class="city-input ui-widget">
                                <input class="tags-city" type="text" placeholder="Город">
                            </div>
                            <input class="btn-search" type="submit" value="искать">
                        </fieldset>
                    <?php ActiveForm::end(); ?>
                </div>
            </div>
            <script id="autocomplete-cities">
                var avaibleCities = JSON.parse('<?= json_encode($cities) ?>');
            </script>
        </div>
        <?php
    }

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }
}