<?php

namespace app\widgets;


use yii\helpers\Html;
use yii\helpers\Url;
use Yii;
use yii\base\Widget;
use yii\widgets\ActiveForm;
use app\models\SiteSearch;
use \app\modules\admin\models\Categories;
use app\models\Cities;

class SearchAdverts extends Widget
{
    public function run()
    {
        $model = \Yii::createObject(SiteSearch::className());
        $categories = Yii::createObject(Categories::className());
        $cities = Yii::createObject(Cities::className())->cities;
        ?>
        <div class="form-search">
            <div class="container">
                <a class="search-query" href="#"><?= Yii::t('app', 'Поисковый запрос')?></a>
                <div class="holder-form-search" data-autocomplete="<?= Url::toRoute('/autocomplete') ?>">
                    <span class="bg-search"></span>
                    <?php $form = ActiveForm::begin([
                            'action' => Url::toRoute('/search'),
                            'method' => 'GET'
                    ]); ?>
                        <fieldset>
                            <a class="closed-search-form" href="#"></a>
                            <?= $form->field($model,'textRequest', ['options' => ['class' => 'search-input', 'tag' => 'div']])
                                ->label(false)
                                ->textInput(['placeholder' => \Yii::t('app', 'Поисковый запрос'), 'name' => 'textRequest'])?>
                            <?= $form->field($model, 'categoryId', ['options' => ['class' => 'category-input', 'tag' => 'div']])
                                ->label(false)
                                ->dropDownList($categories->subAdvertisement, ['class' => 'dropdown',  'name' => 'categoryId', 'prompt' => Yii::t('app','Категория')]) ?>
                            <?= $form->field($model,'city', ['options' => ['class' => 'city-input ui-widget', 'tag' => 'div']])
                                ->label(false)
                                ->textInput(['class' => 'tags-city', 'name' => 'city', 'placeholder' => Yii::t('app', 'Город')])?>

                            <?= Html::submitButton(Yii::t('app', 'Искать'), ['class' => 'btn-search']) ?>
                        </fieldset>
                    <?php ActiveForm::end(); ?>
                </div>
            </div>
            <script id="autocomplete-cities">
                var avaibleCities = JSON.parse('<?= json_encode($cities,JSON_UNESCAPED_UNICODE) ?>');
            </script>
        </div>
        <?php
    }

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }
}