<?php
/**
 * Created by PhpStorm.
 * User: Tony
 * Date: 16.02.2019
 * Time: 15:13
 */

namespace app\widgets;


use yii\base\Widget;

class SearchAdverts extends Widget
{
    public function run()
    {
        ?>
        <div class="form-search">
            <div class="container">
                <a class="search-query" href="#">Поисковый запрос</a>
                <div class="holder-form-search">
                    <span class="bg-search"></span>
                    <form>
                        <fieldset>
                            <a class="closed-search-form" href="#"></a>
                            <div class="search-input">
                                <input type="text" placeholder="Поисковый запрос">
                            </div>
                            <div class="category-input">
                                <select name="dropdown" class="dropdown">
                                    <option>Категория</option>
                                    <option>Категория1</option>
                                    <option>Категория2</option>
                                    <option>Категория3</option>
                                </select>
                            </div>
                            <div class="city-input ui-widget">
                                <input class="tags-city" type="text" placeholder="Город">
                            </div>
                            <input class="btn-search" type="submit" value="искать">
                        </fieldset>
                    </form>
                </div>
            </div>
        </div>
        <?php
    }

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }
}