<?php

namespace app\widgets;


use yii\base\Widget;

class SeoBar extends Widget
{
    public $item;
    public $itemData = [];

    public function init() : string
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function run() : string
    {
        parent::run(); // TODO: Change the autogenerated stub
    }
}