<?php
/**
 * Created by PhpStorm.
 * User: Tony
 * Date: 01.02.2019
 * Time: 12:57
 */

namespace app\widgets;


use yii\base\Widget;

class ShareButtons extends Widget
{
    public $options = [];
    
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function run()
    {
        parent::run(); // TODO: Change the autogenerated stub
    }
}