<?php
/**
 * Created by PhpStorm.
 * User: Tony
 * Date: 20.02.2019
 * Time: 22:12
 */

namespace app\models;


use yii\base\Model;

class SiteSearch extends Model
{
    public $textRequest;
    public $categoryId;
    public $city;

    public function rules()
    {
        return [
            [['textRequest', 'city'], 'string'],
            ['categoryId', 'integer']
        ];
    }

    public function validate($attributeNames = null, $clearErrors = true)
    {
        return parent::validate($attributeNames, $clearErrors); // TODO: Change the autogenerated stub
    }


}